'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { evaluate, normalizeHandle } = require('../src/detector.js');

const v = (o) => Object.assign({ title: '', description: '', hashtags: [], channel: '', channelId: '', labels: [], text: '' }, o);
const at = (sensitivity, extra) => Object.assign({ sensitivity }, extra);

test('platform disclosure labels are always flagged', () => {
  const yt = v({ title: 'Lion vs elephant', text: 'How this content was made Altered or synthetic content Sound or visuals were significantly edited' });
  const tt = v({ description: 'cute puppy', labels: ['AI-generated'] });
  const tt2 = v({ description: 'dance', text: 'Creator labeled as AI-generated' });
  for (const s of ['relaxed', 'balanced', 'strict']) {
    assert.equal(evaluate(yt, at(s)).isAI, true, s);
    assert.equal(evaluate(tt, at(s)).isAI, true, s);
    assert.equal(evaluate(tt2, at(s)).isAI, true, s);
  }
});

test('AI generator hashtags are flagged', () => {
  const r = evaluate(v({ title: 'Cat saves baby from bear 😱 #sora #aivideo' }), at('relaxed'));
  assert.equal(r.isAI, true);
  assert.ok(r.reasons.some((x) => x.includes('#sora')));
  assert.equal(evaluate(v({ description: 'grandma at the beach', hashtags: ['veo3'] }), at('balanced')).isAI, true);
});

test('creator phrases like "made with AI" are flagged', () => {
  for (const t of ['Ancient Rome in 4K (made with AI)', 'Fully AI short film', 'This AI-generated trailer', 'created using Midjourney and Kling', 'Generated by Sora 2']) {
    assert.equal(evaluate(v({ title: t }), at('balanced')).isAI, true, t);
  }
});

test('unicode font tricks are normalized', () => {
  assert.equal(evaluate(v({ title: 'Dragon over Tokyo #𝗮𝗶𝘃𝗶𝗱𝗲𝗼' }), at('balanced')).isAI, true);
});

test('#ai alone only trips strict mode', () => {
  const vid = v({ title: 'Grandma rides a shark #ai' });
  assert.equal(evaluate(vid, at('strict')).isAI, true);
  assert.equal(evaluate(vid, at('balanced')).isAI, false);
});

test('videos about AI are not flagged', () => {
  for (const t of [
    'AI news: OpenAI announces new model',
    'I tried Sora 2 for a week — honest review',
    'How to spot AI generated videos',
    'Veo 3 vs Sora 2 comparison',
    'What is artificial intelligence? Explained',
  ]) {
    assert.equal(evaluate(v({ title: t }), at('balanced')).isAI, false, t);
  }
});

test('ambiguous words do not trigger', () => {
  for (const t of ['Kingdom Hearts: Sora vs Riku boss fight', 'Paris fashion week runway highlights', 'yo veo la playa', 'Pikachu evolves!', 'Thai street food tour', 'Waikiki sunset']) {
    for (const s of ['balanced', 'strict']) assert.equal(evaluate(v({ title: t }), at(s)).isAI, false, `${t} @ ${s}`);
  }
});

test('creators saying "no AI" are respected', () => {
  assert.equal(evaluate(v({ title: 'Real footage, no AI #aivideo debate' }), at('balanced')).isAI, false);
});

test('AI-named channels add weight', () => {
  const vid = v({ title: 'Ancient Egypt like you have never seen', channel: 'Dreamscape AI', channelId: '@dreamscapeai' });
  assert.equal(evaluate(vid, at('relaxed')).isAI, false);
  assert.equal(evaluate(v({ ...vid, hashtags: ['ai'] }), at('balanced')).isAI, true);
  // "kai" / "thai" must not count as an AI handle
  assert.equal(evaluate(v({ title: 'hello', channelId: '@chefkai' }), at('strict')).score, 0);
});

test('block and trust lists override scoring', () => {
  const vid = v({ title: 'Ocean waves', channelId: '@Calm.Videos' });
  assert.equal(evaluate(vid, at('relaxed', { blockedChannels: ['calm.videos'] })).isAI, true);
  const labeled = v({ title: 'x', channelId: '@trusted', labels: ['AI-generated'] });
  assert.equal(evaluate(labeled, at('strict', { allowedChannels: ['@trusted'] })).isAI, false);
});

test('custom keywords', () => {
  assert.equal(evaluate(v({ title: 'peak #aislop moment' }), at('balanced', { customKeywords: ['#aislop'] })).isAI, true);
});

test('ordinary videos stay clean', () => {
  for (const t of ['My morning routine', 'Lakers vs Celtics highlights', 'Easy 15 minute pasta']) {
    const r = evaluate(v({ title: t, channel: 'Some Creator', channelId: '@somecreator' }), at('strict'));
    assert.equal(r.isAI, false, t);
    assert.equal(r.score, 0, t);
  }
});

test('normalizeHandle', () => {
  assert.equal(normalizeHandle('/@Foo.Bar/videos'), '@foo.bar');
  assert.equal(normalizeHandle('https://www.tiktok.com/@abc?lang=en'), '@abc');
  assert.equal(normalizeHandle('xyz'), '@xyz');
  assert.equal(normalizeHandle(''), '');
});
